name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  BICEP_VERSION: 0.24.24

jobs:
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: false

  lint-bicep:
    name: Lint Bicep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Bicep
        uses: anthony-c-martin/setup-bicep@v0.3
        with:
          version: ${{ env.BICEP_VERSION }}

      - name: Lint Bicep
        run: |
          bicep lint ./deploy/main.bicepparam --diagnostics-format sarif > bicep.sarif

      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          category: bicep
          sarif_file: bicep.sarif
