name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  AZCLI_VERSION: 2.55.0
  BICEP_VERSION: 0.24.24

jobs:
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src
          push: false

  lint-bicep:
    name: Lint Bicep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Lint Bicep
        uses: azure/CLI@v1
        with:
          azcliversion: ${{ env.AZCLI_VERSION }}
          inlineScript: |
            az bicep install --version v${{ env.BICEP_VERSION }}
            ~/.azure/bin/bicep lint ./deploy/main.bicepparam --diagnostic-format sarif > bicep.sarif

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
            sarif_file: bicep.sarif
